.github/workflows/deploy-web-dev.yml, .github/workflows/pr-review.yml
ref https://github.com/FirebaseExtended/action-hosting-deploy/blob/main/src/postOrUpdateComment.ts
=> feat: Add function to comment preview link

lib/app.dart
- Reflection of changes since go_router v5 and modification of code
- https://github.com/flutter/packages/commit/b2a4157f80827e0d4f1432247702206a05e44445#diff-7238fb36455c51a44587997e837e9d90d27fb32aeec03a42a966759f6545055f
- packages/go_router/example/lib/main.dart
=> refactor: go_router v5

lib/l10n/localization_ja.dart
https://github.com/FlutterKaigi/conference-app-2023/issues/131
=> fix(l10n): change url scheme

.github/workflows/deploy-web-dev.yml
preview link用にアップロードした、flutter webのアーティファクトを、action上でDL後に削除するよう変更。
Fixes # (issue)
none.
=> feat: Delete used artifact

.run/dev.run.xml
=> ci: Remove .run directory

.run/dev.run.xml
Reverts FlutterKaigi/conference-app-2023#148
=> Revert "ci: Remove .run directory"

README.ja.md, README.md
=> doc: Add go_router_builder

pubspec.lock, pubspec.yaml
* flutter beta 3.15
* google_fonts v6
* permission_handler v11
Fixes none
see preview link.
=> flutter beta 3.15

ios/Podfile.lock, pubspec.lock, pubspec.yaml
* flutter_gen v5.3.2
* go_router v11.0.0
Fixes none
build and run.
=> update: libs

lib/model/remote_config.dart, lib/model/sessions/session.dart, lib/model/sessions/session.freezed.dart, lib/model/sessions/session.g.dart, lib/model/sessions/session_provider.dart, lib/model/sessions/session_provider.g.dart
* Add Session/Speaker/SessionData type
* Add sessionProvider/sessionsProvider/SessionDataProvider
Refs #17 #18 
=> feat: Add session type and providers

.gitattributes
Hide auto-generated files from diff on pull request.
=> Hide auto-generated files from diff on pull request

lib/model/sessions/session.dart, lib/model/sessions/session.freezed.dart, lib/model/sessions/session.g.dart
* Update session data model
Fixes none
none.
=> feat: Add LocaleText, url

pubspec.lock, pubspec.yaml
https://pub.dev/packages/flutter_local_notifications/changelog#1600
=> update: flutter_local_notifications v16

web/.well-known/apple-app-site-association, web/.well-known/assetlinks.json
https://developer.android.com/training/app-links/verify-android-applinks
https://developer.apple.com/documentation/xcode/supporting-associated-domains
Refs #176
no tests.
=> feat: Add whell-known directory

.github/workflows/deploy-web.yml, dart_defines/pro.json, lib/ui/screen/venue/location_map.dart, lib/ui/screen/venue/venue.dart, lib/ui/screen/venue/venue_dev_dummy.dart, pubspec.lock, pubspec.yaml
* Add location map
* Enable google static map (production only)
* Update deploy action
Refs #20
=> location map

android/app/build.gradle, android/app/src/main/AndroidManifest.xml
https://developer.android.com/training/app-links/verify-android-applinks
Fixes #176
Local tests.
=> Android App Links

web/manifest.json
* Set related_application (Android)
https://developer.mozilla.org/ja/docs/Web/Manifest/related_applications
Refs #81
none.
=> feat: Set related_application (Android)

pubspec.lock, pubspec.yaml
* flutter 3.16.0-0.1.pre
build.
=> update: flutter 3.16.0-0.1.pre

.github/workflows/deploy-web.yml, .github/workflows/pr-review.yml
* Update actions/checkout@v4
Fixes none
none.
=> chore: actions/checkout@v4

lib/l10n/localization.dart, lib/l10n/localization_en.dart, lib/l10n/localization_ja.dart, lib/model/remote_config.dart, lib/model/venue/lunch.dart, lib/model/venue/lunch.freezed.dart, lib/model/venue/lunch.g.dart, lib/model/venue/lunch_provider.dart, lib/model/venue/lunch_provider.g.dart, lib/ui/screen/venue/lunch_map.dart, lib/ui/screen/venue/venue.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml
* Add lunch map
* Added remote config key for lunch stores, and add json parsing process
Refs #20
Local build.
=> feat: Add lunch map

android/app/src/main/AndroidManifest.xml
=> chore: Modify deeplink config

lib/model/sessions/session.dart
* Japanese-only display until a multilingual resource is available.
=> chore: Temporarily restricted to ja only

lib/model/sessions/session.dart, lib/model/sessions/session_provider.dart, lib/model/sessions/session_provider.g.dart, lib/ui/screen/sessions/session_detail.dart, lib/ui/screen/sessions/sessions.dart
=> Apply room name alias.

.github/workflows/deploy-web-dev.yml
=> feat: Set PR_NUMBER as environment variable

.github/workflows/deploy-web-dev.yml
=> Read pr and head sha from preview flow

.github/workflows/deploy-web-dev.yml, .github/workflows/pr-review.yml
=> fix: Generate preview environment according to PR number

lib/l10n/localization.dart, lib/l10n/localization_en.dart, lib/l10n/localization_ja.dart, lib/ui/screen/home.dart, lib/ui/screen/sessions/session_detail.dart, lib/ui/screen/sponsors/sponsor_item.dart, lib/ui/screen/sponsors/sponsors.dart, lib/ui/screen/venue/venue.dart
* Add semantic labels
* Add tooltips
Refs #71
Use the talkback feature on my Android device.
=> feat: Add tooltips and semantic labels

ios/Podfile, ios/Podfile.lock, pubspec.lock, pubspec.yaml
* Update flutter and ios project
https://pub.dev/packages/go_router/changelog#1200
Refs #90 
Build.
=> chore: Update flutter and ios project

ios/ExportOptions/pro.plist, ios/Runner/Runner-pro.entitlements, pubspec.yaml
* Fix aps-environment mode
* Update version code
=> fix: fcm settings

fastlane/Fastfile
* Modify upload_to_app_store options
=> fix: fastlane option

ios/Runner/Info.plist, pubspec.yaml
* TestFlight crashes when launching the app, so try a version with Impeller disabled once.
=> disable impeller

ios/Runner/Info.plist
=> feat: Enable Impeller

lib/model/messaging.dart
* To address crashes in the iOS release build distributed through TestFlight, identify and implement necessary fixes.
=> fix: Ensure proper token retrieval for FCM to avoid crashes

pubspec.yaml
=> chore: VersionCode 13

web/manifest.json
https://developer.mozilla.org/en-US/docs/Web/Manifest/related_applications
Fixes none
Check preview page.
=> chore: Add ios application

lib/ui/router/branch/router_app_sessions.dart
画面遷移方法を変更したことで、不要になったMaterialを削除しました。
https://github.com/FlutterKaigi/conference-app-2023/pull/173#discussion_r1349899729
Fixes none
ローカル環境で確認。
=> refactor: Remove unnecessary Material

pubspec.yaml
=> chore: 1.1.0+14

lib/ui/screen/sessions/session_detail.dart, lib/ui/widget/session_card.dart
* Primary color is specified for the button to add favorite session.
Fixes none
Preview link.
=> feat: Tint icons

android/app/src/dev/google-services.json, ios/Config/dev/GoogleService-Info.plist
* Update google-service.json and GoogleService-info.plist. 
Fixes none
Local build.
=> chore: Update firebase config

lib/l10n/localization_en.dart
1. This PR corrects English localization.
2. Modifying some singular words to plural words
=> fix: english typo

lib/l10n/localization.dart, lib/l10n/localization_en.dart, lib/l10n/localization_ja.dart, lib/ui/screen/venue/floor_map.dart
* Show floor map
Fixes #20 
Check the preview.
=> feat: Show floor map

lib/ui/screen/home.dart, lib/ui/screen/root.dart
- Delete selection area from RootScreen.
- Put selection area on HomeScreen while on web.
Fixes #235
=> Delete selection area from RootScreen.

ios/Podfile.lock, pubspec.lock
=> chore: Update packages

pubspec.yaml
=> chore: 1.2.0+15

pubspec.yaml
=> chore: VersionCode 16

android/app/build.gradle
=> fix: Use "

lib/model/favorites/favorite_session_ids.dart, lib/model/favorites/favorite_session_ids.g.dart, lib/model/favorites/favorite_session_provider.dart, lib/model/favorites/favorite_session_provider.g.dart, lib/model/sessions/session_provider.dart, lib/model/venue/lunch.dart, lib/ui/screen/contributors/staffs.dart, lib/ui/screen/root.dart, lib/ui/screen/root_tab.dart, lib/ui/screen/sessions/sessions.dart
* Add trailing comma
* Remove `SelectionContainer.disabled` widget
* Add static `current` function to RootTab class
Fixes noen
Local build and check the application.
=> refactor: Check code style, remove unncessary code

lib/l10n/localization.dart, lib/l10n/localization_en.dart, lib/l10n/localization_ja.dart, lib/model/firebase_crashlytics.dart, lib/model/firebase_crashlytics.g.dart, lib/model/remote_config.dart, lib/model/root/questionnaire.dart, lib/model/root/questionnaire.freezed.dart, lib/model/root/questionnaire.g.dart, lib/model/root/questionnaire_provider.dart, lib/model/root/questionnaire_provider.g.dart, lib/ui/screen/root.dart, lib/ui/widget/session_questionnaire_fab.dart, lib/util/firebase.dart, pubspec.lock
=> Show session questionnaire fab

lib/app.dart, lib/main.dart, lib/util/firebase.dart
=> fix: Avoid error at web build

pubspec.yaml
=> chore: 1.3.0+17

pubspec.yaml
=> chore: 1.3.0+18

ios/Podfile.lock, linux/flutter/generated_plugin_registrant.cc, linux/flutter/generated_plugins.cmake, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
=> Remove image picker.

lib/ui/screen/sessions/session_detail.dart, pubspec.lock, pubspec.yaml
* Update package
* Code cleanup
Fixes none
=> chore: Update and cleanup

pubspec.lock, pubspec.yaml
=> chore: 1.4.0+20

ios/Runner/Info.plist, pubspec.yaml
=> Fix store review points
